# Generated by Django 4.1.2 on 2022-10-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Candidate',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
