# Generated by Django 4.1.2 on 2022-10-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_last_name_candidate_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
