# Generated by Django 4.1.2 on 2022-10-05 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2022, 10, 5, 2, 43, 12, 218256, tzinfo=datetime.timezone.utc), max_length=18),
            preserve_default=False,
        ),
    ]
