# Generated by Django 4.1.2 on 2022-10-05 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2022, 10, 5, 17, 7, 28, 7473, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
