# Generated by Django 4.1.2 on 2022-10-05 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default=datetime.datetime(2022, 10, 5, 21, 45, 5, 459149, tzinfo=datetime.timezone.utc), max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('I am outgoing', ' I am outgoing'), ('', 'Select a personality'), ('I am discreet', 'I am discreet'), ('I am social', 'I am social'), ('I am antisocial', 'I am antisocial'), ('I am serious', 'I am serious')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.CharField(default=datetime.datetime(2022, 10, 5, 21, 45, 17, 138854, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('2', 'No'), ('1', 'Yes')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Approved', 'Approved')], default='Pending', max_length=50, null=True),
        ),
    ]
