# Generated by Django 4.1.2 on 2022-10-06 19:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_candidate_frameworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MySql', 'MySql'), ('postgres', 'Postgres'), ('MongoDB', 'MongoDB'), ('SqLite3', 'SqLite3'), ('Oracle', 'Oracle'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'Ajax'), ('JQuery', 'JQuery'), ('React.js', 'React.js'), ('Chart.js', 'Chart.js'), ('Gsap', 'Gsap'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React native', 'React native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Ionic', 'Ionic'), ('Xamarim', 'Xamarim'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('SQL', 'SQL'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Others', 'Others')], default='', max_length=50),
        ),
    ]
