# Generated by Django 4.1.2 on 2022-10-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company_note',
            field=models.TextField(blank=True),
        ),
    ]
