# Generated by Django 4.1.2 on 2022-10-07 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_candidate_company_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 0, 7, 46, 265527, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
