# Generated by Django 4.1.2 on 2022-10-07 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_candidate_age_candidate_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about_about',
            field=models.TextField(default=datetime.datetime(2022, 10, 7, 0, 37, 24, 958733, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='about_course',
            field=models.TextField(default=datetime.datetime(2022, 10, 7, 0, 37, 36, 777584, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(default=datetime.datetime(2022, 10, 7, 0, 37, 46, 866532, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(default=datetime.datetime(2022, 10, 7, 0, 37, 59, 15041, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='employed',
            field=models.BooleanField(null=True, verbose_name='I am employed'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_course',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 0, 38, 11, 537499, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_job',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 0, 38, 23, 704621, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(default=datetime.datetime(2022, 10, 7, 0, 38, 33, 253899, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default=datetime.datetime(2022, 10, 7, 0, 38, 44, 337572, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='remote',
            field=models.BooleanField(null=True, verbose_name='I agree to work remotely'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_course',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 0, 38, 53, 685222, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_job',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 0, 39, 2, 599222, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_course',
            field=models.CharField(choices=[('', 'Select your status'), ("I'm studying", "I'm studying"), ('I took a break', 'I took a break'), ('Completed', 'Completed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='travel',
            field=models.BooleanField(null=True, verbose_name="I'm available for travel"),
        ),
    ]
