# Generated by Django 4.1.2 on 2022-10-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_candidate_image_alter_candidate_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='about_about',
            new_name='about_job',
        ),
    ]
